In [66]:
#THEORETICAL QUESTIONS

In [67]:
#1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
# enhance Python's capabilities for numerical operations?


In [68]:
#ans: Numpy is a core library for numerical computing in python, providing efficient multi-dimensional array operations
# and mathematical functions.It enhances python's performance with vectorized operations and memory-efficient data structures.
#Numpy supports advanced operations like linear algebra and random number generation, and integrates with other scientific libraries,
#making it essential for data analyisis and scientific computing

In [69]:
#2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

In [ ]:
#ans: np.mean() and np.average() both calculate the average of array elements, but np.average() offers aditional functionality such as weighting
#we can use np.mean() for simple average calculations while np.average() for when you need to compute a weighted average as it allows specifying
#weights for the elements.

In [72]:
#example:
arr=np.array([1,2,3,4,5])
print('mean:',np.mean(arr))
weights=np.array([1,1,1,1,2])
print('weighted_average',np.average(arr,weights=weights))# it is calcualted as (1*1+2*1+3*1+4*1+5*2)/(1+1+1+1+2) where 5 has higher weights

mean: 3.0
weighted_average 3.3333333333333335


In [ ]:
#3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

In [73]:
#ans:To reverse a numpy array along different axes:
# 1D array: we can use slicing with [::-1] to reverse the array
#2D array: we can use slicing to reverse along specific axes, example:[::-1] for rows and [:,::-1] for columns

In [ ]:
#example:
arr=np.array([1,2,3,4,5,6])
arr_rev=arr[::-1]
print(arr)
print(arr_rev)
print()
arr_2d=np.array([1,2],[3,4])
arr_2d_rev=arr_2d[::-1]#2d rows wise reverse
arr_2d_rev2=arr_2d[:,::-1]#2d column reverse

In [ ]:
#4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
# in memory management and performance

In [74]:
#ans: we can determine the data type of elements in a numpy array by using arr.dtype atrribut:
arr=np.array([1,2,3,4,5])
print('data type of arr is:',arr.dtype)
#importance of data types:
#Memory management: data types determine how much memory each element occupies.ex: np.int32 uses 4 bytes while np.float 64 uses 8 byte
#Performance: operations on array with smaller data types(like np.float32 instead of np.float64) can be faster and more efficient as they require less computinal
#power and memory bandwidth

data type of arr is: int64


In [ ]:
#5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In [ ]:
#ans:ndarrays (n-dimensional array) in Numpy is a powerfull data structure with the following key features:
#multi-dimensional:supports arrays of any dimension
# Homogenous: all elements are of the same data type
#vectorized operations: enables fast-element-wise operations without explicit loops
#Differences from python lists:
#Performance: ndarray is faster and more memory-efficient
#Homogeneity:ndarray requires a single data type,unlike python lists
#Functionality:ndarray offers extesive mathematical and statistical functions.


In [ ]:
#6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

In [ ]:
#Numpy arrays are faster and more efficient than python lists for large-scale numerical tasks because:
#speed:Numpy operations run faster due to optimized c code
#vectorization: Numpy can preform calcualations on entire arrays at once,avoiding slow loops.
#Memory efficiency: Numpy arrays use less memory by storing data more compactly.

In [ ]:
#7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

In [77]:
#vstack() and hstack() are Numpy functions used for stacking arrays vertically and horizontally, respectively:
#vstack():stacks arrays vertically(row-wise)
#hstack():stacks arrays hortizontally(column-wise)
#example:
a=np.array([[1,2],[3,4]])
b=np.array([5,6],ndmin=2)
#vertical arrays:
vstack_result=np.vstack((a,b))
#horizontal stack
hstack_result=np.hstack((a,b.T))

print(vstack_result)
print(hstack_result)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [78]:
#8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

In [82]:
#fliplr() and flipud() are numpy methods used to flip arrays:
# fliplr(): Flips the array horizontally(left to right), affecting only 2D arrays or higher.
#flipud():Flips the array vertically(top to bottom) affecting 1D arrays and higher.
#Effects:
#fliplr():Reverses the order of columns.
#flipud():Reverses the order of rows
#exsmple:
a=np.arange(6).reshape(2,3)
print('original array\n',a)
print('fliplr result\n',np.fliplr(a))
print('flipud result\n',np.flipud(a))


original array
 [[0 1 2]
 [3 4 5]]
fliplr result
 [[2 1 0]
 [5 4 3]]
flipud result
 [[3 4 5]
 [0 1 2]]


In [ ]:
#9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [83]:
#ans: The array_split() method in Numpy splits an array into multiple sub-arrays. Unlike split() it handles
# eneven splits by distributing the remainder among the first few sub-arrays.
#example:
arr=np.arange(9)
arr_split=np.array_split(arr,3)
print('original array:',arr)
print('splited_array:',arr_split)# array after using np.array_split() it divide whole array into 3 pieces

original array: [0 1 2 3 4 5 6 7 8]
splited_array: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [ ]:
#10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

In [84]:
# Vectorization:
#--Applies operations to entire arrays at once,bypassing the need for loops.
#--it is significantly faster than looping through elements individually.

#Broadcasting:
#--Allows operations on arrays of different shapes by expanding smaller arrays to match larger ones.
#--it simplifies code and enhances efficiency withour extra memory usage

##contribution and efficiency:
#speed:Operations are executed faster
#memory: broadcasting avoids extra copies, saving memory and imporving performance.

In [65]:
##Practical questions

In [2]:
import numpy as np
import pandas as pd

In [3]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [9]:
a=np.random.randint(1,101,(3,3))
print(a)

array([[65, 29, 45],
       [ 9,  9, 30],
       [44, 29, 90]])

In [10]:
new_array=a.T
print(new_array)

array([[65,  9, 44],
       [29,  9, 29],
       [45, 30, 90]])

In [11]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [12]:
b=np.arange(10)

In [14]:
c=b.reshape(2,5)#reshapeing b into(2*5)

In [62]:
c.reshape(5,2)# reshaping c into (5*2)
print(b)
print(c)
print(c.reshape(5,2))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [63]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [64]:
d=np.random.random((4,4))

In [18]:
print(d)

array([[0.36250702, 0.39262499, 0.62267986, 0.3300217 ],
       [0.35472351, 0.62378034, 0.13510183, 0.8908689 ],
       [0.96437733, 0.2634582 , 0.66545545, 0.73572646],
       [0.65111314, 0.21294461, 0.04023605, 0.08619037]])

In [22]:
e=np.zeros((6,6))

In [23]:
e[1:-1,1:-1]=d

In [27]:
print(e)
print(e.shape)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.36250702 0.39262499 0.62267986 0.3300217  0.        ]
 [0.         0.35472351 0.62378034 0.13510183 0.8908689  0.        ]
 [0.         0.96437733 0.2634582  0.66545545 0.73572646 0.        ]
 [0.         0.65111314 0.21294461 0.04023605 0.08619037 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]
(6, 6)


In [28]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [29]:
arr=np.arange(10,61,5)

In [31]:
print(arr)
print(type(arr))

[10 15 20 25 30 35 40 45 50 55 60]
<class 'numpy.ndarray'>


In [32]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
# (uppercase, lowercase, title case, etc.) to each element.

In [33]:
arr=np.array(['python', 'numpy', 'pandas'])

In [35]:
arr_uppercase=np.char.upper(arr)
print(arr_uppercase)
arr_lowercase=np.char.lower(arr)
print(arr_lowercase)
arr_titlecase=np.char.title(arr)
print(arr_titlecase)

['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


In [36]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [37]:
arr=np.array(['my','name','is','khan'])
new_arr=np.char.join(' ',arr)
print(arr)
print(new_arr)

['my' 'name' 'is' 'khan']
['m y' 'n a m e' 'i s' 'k h a n']


In [38]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [39]:
arr1=np.arange(6).reshape(2,3)
arr2=np.arange(6,12).reshape(2,3)

In [40]:
#addition
print(arr1+arr2)
#substraction
print(arr2-arr1)
#multiplication
print(arr1*arr2)
#division
print(arr1/arr2)

[[ 6  8 10]
 [12 14 16]]
[[6 6 6]
 [6 6 6]]
[[ 0  7 16]
 [27 40 55]]
[[0.         0.14285714 0.25      ]
 [0.33333333 0.4        0.45454545]]


In [41]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [48]:
arr=np.identity(5,dtype=int)
#extracting daigonal elements
arr_new=np.diag(arr)

print(arr)
print(arr_new)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[1 1 1 1 1]


In [49]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array


In [52]:
def is_prime(num):
  if num<2:
    return False
  for i in range(2,int(np.sqrt(num))+1):
    if num%i==0:
      return False
  return True

arr=np.random.randint(0,1001,size=1000)
#print(arr)
primes=np.array([num for num in arr if is_prime(num)])
print(primes)
print(len(primes))

[487 593 683 691 401 353 811 991 797   7 877 227 197 601 577 991 653 419
 809 419 971 211 109 337 547  89 751 149 823 191  43 937 109 263 827 277
 727   7   7 653 443 353 439 139 709 761 103 173 677 449 401  19  47 619
 223 199 367 149 643 313 691 401 191 733 149  67  61   2  97 131 757 997
 421 163 857 991 103 103 127 853   7 263 199 313 587 251 317  89 547 811
 701  19 443 719  61 281 421 733 373 421 691 577 797  83 823  13 523 229
 197  59 113  11 503 829 373 271 367 877 599 863 733  19 941 683 619 619
 107 617 317 223 137 797 179 271  53   5  41  47 883 149  97 503 457 229
  41 863 683 181 937 809 103]
151


In [53]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [60]:
temp_daily=np.random.uniform(low=20,high=40,size=28)
print(temp_daily)
weekly_temperature=temp_daily.reshape(4,7)
print(weekly_temperature)
average_weekly_temp=np.mean(weekly_temperature)
print(average_weekly_temp)

[31.00290979 34.19879304 34.38683497 21.67204465 24.27996212 36.19576751
 26.8027789  38.60392033 21.88198282 20.57363523 35.45180027 39.14672797
 27.08183482 22.94553888 27.40088995 32.61289531 28.67856483 23.6742664
 26.79665664 38.81449932 28.08843324 23.17943475 25.85082148 39.81813486
 31.62457292 20.19974136 28.57999932 38.81375644]
[[31.00290979 34.19879304 34.38683497 21.67204465 24.27996212 36.19576751
  26.8027789 ]
 [38.60392033 21.88198282 20.57363523 35.45180027 39.14672797 27.08183482
  22.94553888]
 [27.40088995 32.61289531 28.67856483 23.6742664  26.79665664 38.81449932
  28.08843324]
 [23.17943475 25.85082148 39.81813486 31.62457292 20.19974136 28.57999932
  38.81375644]]
29.584185646489
